server.port=8082

spring.application.name=consumer-service

# ---------------- DATABASE ----------------
spring.datasource.url=jdbc:mysql://localhost:3306/kafka_streaming_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Shiva@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# ---------------- JPA ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ---------------- STRIPE ----------------
stripe.api.key=sk_test_51SbxhX7hOyQUa
stripe.webhook.secret=whsec_
stripe.currency=inr
stripe.publishable.key=pk_test_

# ---------------- KAFKA ----------------
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.booking-group=booking-consumer-group
spring.kafka.consumer.analytics-group=analytics-consumer-group
spring.kafka.consumer.dashboard-group=dashboard-consumer-group
spring.kafka.consumer.notification-group=notification-consumer-group
spring.kafka.consumer.payment-group=payment-consumer-group

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.max-poll-records=10

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE

# ---------------- TOPICS ----------------
kafka.topic.booking-events=booking-events
kafka.topic.dashboard-events=dashboard-events
kafka.topic.notification-events=notification-events
kafka.topic.payment-events=payment-events

# ---------------- LOGGING ----------------
logging.level.com.realtime=DEBUG
logging.level.org.apache.kafka=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
