#server.port=8081
#
#spring.application.name=producer-service
#
#
## ---------------- KAFKA ----------------
#
#spring.kafka.bootstrap-servers=localhost:9092
#
## Producer config
#kafka.topic.payment-events=payment-events
#consumer.service.url=http://localhost:8082
#
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.acks=all
#spring.kafka.producer.retries=3
#
## Producer advanced properties
#
#spring.kafka.producer.properties.enable.idempotence=true
#spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
#spring.kafka.producer.properties.linger.ms=10
#spring.kafka.producer.properties.buffer.memory=33554432
#spring.kafka.producer.properties.compression.type=snappy
#
## ---------------- TOPICS ----------------
#
#kafka.topic.booking-events=booking-events
#kafka.topic.dashboard-events=dashboard-events
#kafka.topic.notification-events=notification-events
#
## ---------------- PRODUCER ----------------
#
#kafka.producer.group-id=producer-service
#
## ---------------- LOGGING ----------------
#
#logging.level.com.realtime=DEBUG
#logging.level.org.apache.kafka=WARN
#
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n



server.port=8081

spring.application.name=producer-service

# ---------------- KAFKA ----------------
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.linger.ms=10
spring.kafka.producer.properties.compression.type=snappy

# ---------------- TOPICS ----------------
kafka.topic.booking-events=booking-events
kafka.topic.dashboard-events=dashboard-events
kafka.topic.notification-events=notification-events
kafka.topic.payment-events=payment-events

# ---------------- CONSUMER SERVICE URL ----------------
consumer.service.url=http://localhost:8082

# ---------------- LOGGING ----------------
logging.level.com.realtime=DEBUG
logging.level.org.apache.kafka=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
